logging_level: INFO
tutorial: false

results_dir: results/
summary_dir: results/
costs_dir: data/ #TODO change to the equivalent of technology data

run:
  name: "test_run" # use this to keep track of runs with different settings
  name_subworkflow: ""  # scenario name of the pypsa-earth subworkflow
  shared_cutouts: true  # set to true to share the default cutout(s) across runs
                        # Note: value false requires build_cutout to be enabled

foresight: overnight

# option to disable the subworkflow to ease the analyses
disable_subworkflow: false

scenario:
  simpl: # only relevant for PyPSA-Eur
  - ""
  clusters: # number of nodes in Europe, any integer between 37 (1 node per country-zone) and several hundred
  - 10
  planning_horizons: # investment years for myopic and perfect; or costs year for overnight
  - 2030
  ll:
  - "c1.0"
  opts:
  - "Co2L"
  sopts:
  - "144H"
  demand:
  - "AB"

policy_config:
  hydrogen:
    temporal_matching: "no_res_matching" # either "h2_yearly_matching", "h2_monthly_matching", "no_res_matching"
    spatial_matching: false
    additionality: false # RE electricity is equal to the amount required for additional hydrogen export compared to the 0 export case ("reference_case")
    allowed_excess: 1.0
    is_reference: false # Whether or not this network is a reference case network, relevant only if additionality is _true_
    remove_h2_load: false # Whether or not to remove the h2 load from the network, relevant only if is_reference is _true_
    path_to_ref: "" # Path to the reference case network for additionality calculation, relevant only if additionality is _true_ and is_reference is _false_
    re_country_load: false # Set to "True" to force the RE electricity to be equal to the electricity required for hydrogen export and the country electricity load. "False" excludes the country electricity load from the constraint.

clustering_options:
  alternative_clustering: true

countries: ['MA']

demand_data:
  update_data: true # if true, the workflow downloads the energy balances data saved in data/demand/unsd/data again. Turn on for the first run.
  base_year: 2019

  other_industries: false # Whether or not to include industries that are not specified. some countries have has exaggerated numbers, check carefully.
  aluminium_year: 2019 # Year of the aluminium demand data specified in `data/AL_production.csv`


enable:
  retrieve_cost_data: true # if true, the workflow overwrites the cost data saved in data/costs again
  retrieve_irena: true  #If true, downloads the IRENA data

fossil_reserves:
  oil: 100 # TWh Maybe redundant


export:
  h2export: [10] # Yearly export demand in TWh
  store: true # [True, False] # specifies whether an export store to balance demand is implemented
  store_capital_costs: "no_costs" # ["standard_costs", "no_costs"] # specifies the costs of the export store. "standard_costs" takes CAPEX of "hydrogen storage tank type 1 including compressor"
  export_profile: "ship" # use "ship" or "constant"
  ship:
    ship_capacity: 0.4 # TWh # 0.05 TWh for new ones, 0.003 TWh for Susio Frontier, 0.4 TWh according to Hampp2021: "Corresponds to 11360 t H2 (l) with LHV of 33.3333 Mwh/t_H2. Cihlar et al 2020 based on IEA 2019, Table 3-B"
    travel_time: 288 # hours # From Agadir to Rotterdam and back (12*24)
    fill_time: 24 # hours, for 48h see Hampp2021
    unload_time: 24 # hours for 48h see Hampp2021

custom_data:
  renewables: [] # ['csp', 'rooftop-solar', 'solar']
  elec_demand: false
  heat_demand: false
  industry_demand: false
  industry_database: false
  transport_demand: false
  water_costs: false
  h2_underground: false
  add_existing: false
  custom_sectors: false
  gas_network: false # If "True" then a custom .csv file must be placed in "resources/custom_data/pipelines.csv" , If "False" the user can choose btw "greenfield" or Model built-in datasets. Please refer to ["sector"] below.


costs: # Costs used in PyPSA-Earth-Sec. Year depends on the wildcard planning_horizon in the scenario section
  version: v0.6.2
  lifetime: 25 # default lifetime
  # From a Lion Hirth paper, also reflects average of Noothout et al 2016
  discountrate: [0.071] #, 0.086, 0.111]
  # [EUR/USD] ECB: https://www.ecb.europa.eu/stats/exchange/eurofxref/html/eurofxref-graph-usd.en.html # noqa: E501
  USD2013_to_EUR2013: 0.7532

  # Marginal and capital costs can be overwritten
  # capital_cost:
  #   onwind: 500
  marginal_cost:
    solar: 0.01
    onwind: 0.015
    offwind: 0.015
    hydro: 0.
    H2: 0.
    battery: 0.

  emission_prices: # only used with the option Ep (emission prices)
    co2: 0.

  lines:
    length_factor: 1.25 # to estimate offwind connection costs


industry:
  reference_year: 2015

solar_thermal:
  clearsky_model: simple
  orientation:
    slope: 45.
    azimuth: 180.

existing_capacities:
  grouping_years_power: [1960, 1965, 1970, 1975, 1980, 1985, 1990, 1995, 2000, 2005, 2010, 2015, 2020, 2025, 2030]
  grouping_years_heat: [1980, 1985, 1990, 1995, 2000, 2005, 2010, 2015, 2019] # these should not extend 2020
  threshold_capacity: 10
  default_heating_lifetime: 20
  conventional_carriers:
  - lignite
  - coal
  - oil
  - uranium

sector:
  gas:
    spatial_gas: true # ALWAYS TRUE
    network: false # ALWAYS FALSE for now (NOT USED)
    network_data: GGIT # Global dataset -> 'GGIT' , European dataset -> 'IGGIELGN'
    network_data_GGIT_status: ['Construction', 'Operating', 'Idle', 'Shelved', 'Mothballed', 'Proposed']
  hydrogen:
    network: true
    H2_retrofit_capacity_per_CH4: 0.6
    network_limit: 2000 #GWkm
    network_routes: gas # "gas or "greenfield". If "gas"  ->  the network data are fetched from ["sector"]["gas"]["network_data"]. If "greenfield"  -> the network follows the topology of electrical transmission lines
    gas_network_repurposing: true # If true -> ["sector"]["gas"]["network"] is automatically false
    underground_storage: false
    hydrogen_colors: false
    set_color_shares: false
    blue_share: 0.40
    pink_share: 0.05
  coal:
    shift_to_elec: true # If true, residential and services demand of coal is shifted to electricity. If false, the final energy demand of coal is disregarded

  international_bunkers: false # Whether or not to count the emissions of international aviation and navigation

  oil:
    spatial_oil: true

  district_heating:
    potential: 0.3 # maximum fraction of urban demand which can be supplied by district heating
      # increase of today's district heating demand to potential maximum district heating share
      # progress = 0 means today's district heating share, progress=-1 means maximum fraction of urban demand is supplied by district heating
    progress: 1
      # 2020: 0.0
      # 2030: 0.3
      # 2040: 0.6
      # 2050: 1.0
    district_heating_loss: 0.15
  reduce_space_heat_exogenously: true  # reduces space heat demand by a given factor (applied before losses in DH)
  # this can represent e.g. building renovation, building demolition, or if
  # the factor is negative: increasing floor area, increased thermal comfort, population growth
  reduce_space_heat_exogenously_factor: 0.29 # per unit reduction in space heat demand
  # the default factors are determined by the LTS scenario from http://tool.european-calculator.eu/app/buildings/building-types-area/?levers=1ddd4444421213bdbbbddd44444ffffff11f411111221111211l212221
    # 2020: 0.10  # this results in a space heat demand reduction of 10%
    # 2025: 0.09  # first heat demand increases compared to 2020 because of larger floor area per capita
    # 2030: 0.09
    # 2035: 0.11
    # 2040: 0.16
    # 2045: 0.21
    # 2050: 0.29

  tes: true
  tes_tau: # 180 day time constant for centralised, 3 day for decentralised
    decentral: 3
    central: 180
  boilers: true
  oil_boilers: false
  chp: true
  micro_chp: false
  solar_thermal: true
  heat_pump_sink_T: 55 # Celsius, based on DTU / large area radiators; used un build_cop_profiles.py
  time_dep_hp_cop: true # time dependent heat pump coefficient of performance
  solar_cf_correction: 0.788457 #  = >>>1/1.2683
  bev_plug_to_wheel_efficiency: 0.2 # kWh/km from EPA https://www.fueleconomy.gov/feg/ for Tesla Model S
  bev_charge_efficiency: 0.9 # BEV (dis-)charging efficiency
  transport_heating_deadband_upper: 20.
  transport_heating_deadband_lower: 15.
  ICE_lower_degree_factor: 0.375 # in per cent increase in fuel consumption per degree above deadband
  ICE_upper_degree_factor: 1.6
  EV_lower_degree_factor: 0.98
  EV_upper_degree_factor: 0.63
  bev_avail_max: 0.95
  bev_avail_mean: 0.8
  bev_dsm_restriction_value: 0.75 # Set to 0 for no restriction on BEV DSM
  bev_dsm_restriction_time: 7 # Time at which SOC of BEV has to be dsm_restriction_value
  v2g: true # allows feed-in to grid from EV battery
  bev_dsm: true # turns on EV battery
  bev_energy: 0.05 # average battery size in MWh
  bev_availability: 0.5 # How many cars do smart charging
  transport_fuel_cell_efficiency: 0.5
  transport_internal_combustion_efficiency: 0.3
  industry_util_factor: 0.7

  biomass_transport: true  # biomass transport between nodes
  biomass_transport_default_cost: 0.1 # EUR/km/MWh
  solid_biomass_potential: 40 # TWh/a, Potential of whole modelled area
  biogas_potential: 0.5 # TWh/a, Potential of whole modelled area

  efficiency_heat_oil_to_elec: 0.9
  efficiency_heat_biomass_to_elec: 0.9
  efficiency_heat_gas_to_elec: 0.9

  dynamic_transport:
    enable: false # If "True", then the BEV and FCEV shares are obtained depending on the "Co2L"-wildcard (e.g. "Co2L0.70: 0.10"). If "False", then the shares are obtained depending on the "demand" wildcard and "planning_horizons" wildcard as listed below (e.g. "DF_2050: 0.08")
    land_transport_electric_share:
      Co2L2.0: 0.00
      Co2L1.0: 0.01
      Co2L0.90: 0.03
      Co2L0.80: 0.06
      Co2L0.70: 0.10
      Co2L0.60: 0.17
      Co2L0.50: 0.27
      Co2L0.40: 0.40
      Co2L0.30: 0.55
      Co2L0.20: 0.69
      Co2L0.10: 0.80
      Co2L0.00: 0.88
    land_transport_fuel_cell_share:
      Co2L2.0: 0.01
      Co2L1.0: 0.01
      Co2L0.90: 0.01
      Co2L0.80: 0.01
      Co2L0.70: 0.01
      Co2L0.60: 0.01
      Co2L0.50: 0.01
      Co2L0.40: 0.01
      Co2L0.30: 0.01
      Co2L0.20: 0.01
      Co2L0.10: 0.01
      Co2L0.00: 0.01

  land_transport_fuel_cell_share: # 1 means all FCEVs HERE
    BU_2030: 0.00
    AP_2030: 0.004
    NZ_2030: 0.02
    DF_2030: 0.01
    AB_2030: 0.01
    BU_2050: 0.00
    AP_2050: 0.06
    NZ_2050: 0.28
    DF_2050: 0.08

  land_transport_electric_share: # 1 means all EVs  # This leads to problems when non-zero HERE
    BU_2030: 0.00
    AP_2030: 0.075
    NZ_2030: 0.13
    DF_2030: 0.01
    AB_2030: 0.01
    BU_2050: 0.00
    AP_2050: 0.42
    NZ_2050: 0.68
    DF_2050: 0.011

  co2_network: true
  co2_sequestration_potential: 200 # MtCO2/a sequestration potential for Europe
  co2_sequestration_cost: 10 # EUR/tCO2 for sequestration of CO2
  hydrogen_underground_storage: true
  shipping_hydrogen_liquefaction: false
  shipping_average_efficiency: 0.4 # For conversion of fuel oil to propulsion in 2011

  shipping_hydrogen_share: # 1.0
    BU_2030: 0.00
    AP_2030: 0.00
    NZ_2030: 0.10
    DF_2030: 0.05
    AB_2030: 0.05
    BU_2050: 0.00
    AP_2050: 0.25
    NZ_2050: 0.36
    DF_2050: 0.12

  gadm_level: 1
  h2_cavern: true
  marginal_cost_storage: 0
  methanation: true
  helmeth: true
  dac: true
  SMR: true
  SMR CC: true
  cc_fraction: 0.9
  cc: true
  space_heat_share: 0.6 # the share of space heating from all heating. Remainder goes to water heating.
  airport_sizing_factor: 3

  min_part_load_fischer_tropsch: 0.9

  conventional_generation: # generator : carrier
    OCGT: gas
    # Gen_Test: oil # Just for testing purposes

# snapshots are originally set in PyPSA-Earth/config.yaml but used again by PyPSA-Earth-Sec
snapshots:
  # arguments to pd.date_range
  start: "2013-01-01"
  end: "2014-01-01"
  inclusive: "left" # end is not inclusive

# atlite:
#   cutout: ./cutouts/africa-2013-era5.nc

build_osm_network:  # TODO: To Remove this once we merge pypsa-earth and pypsa-earth-sec
  force_ac: false  # When true, it forces all components (lines and substation) to be AC-only. To be used if DC assets create problem.

solving:
  # tmpdir: "path/to/tmp"
  options:
    formulation: kirchhoff
    clip_p_max_pu: 1.e-2
    load_shedding: false
    noisy_costs: true
    skip_iterations: true
    track_iterations: false
    min_iterations: 4
    max_iterations: 6

  solver:
    name: gurobi
    options: gurobi-default

  solver_options:
    highs-default:
      # refer to https://ergo-code.github.io/HiGHS/dev/options/definitions/
      threads: 4
      solver: "ipm"
      run_crossover: "off"
      small_matrix_value: 1e-6
      large_matrix_value: 1e9
      primal_feasibility_tolerance: 1e-5
      dual_feasibility_tolerance: 1e-5
      ipm_optimality_tolerance: 1e-4
      parallel: "on"
      random_seed: 123
    gurobi-default:
      threads: 4
      method: 2 # barrier
      crossover: 0
      BarConvTol: 1.e-6
      Seed: 123
      AggFill: 0
      PreDual: 0
      GURO_PAR_BARDENSETHRESH: 200
    gurobi-numeric-focus:
      NumericFocus: 3       # Favour numeric stability over speed
      method: 2             # barrier
      crossover: 0          # do not use crossover
      BarHomogeneous: 1     # Use homogeneous barrier if standard does not converge
      BarConvTol: 1.e-5
      FeasibilityTol: 1.e-4
      OptimalityTol: 1.e-4
      ObjScale: -0.5
      threads: 8
      Seed: 123
    gurobi-fallback:        # Use gurobi defaults
      crossover: 0
      method: 2             # barrier
      BarHomogeneous: 1     # Use homogeneous barrier if standard does not converge
      BarConvTol: 1.e-5
      FeasibilityTol: 1.e-5
      OptimalityTol: 1.e-5
      Seed: 123
      threads: 8
    cplex-default:
      threads: 4
      lpmethod: 4 # barrier
      solutiontype: 2 # non basic solution, ie no crossover
      barrier.convergetol: 1.e-5
      feasopt.tolerance: 1.e-6
    copt-default:
      Threads: 8
      LpMethod: 2
      Crossover: 0
    cbc-default: {} # Used in CI
    glpk-default: {} # Used in CI

  mem: 30000 # memory in MB; 20 GB enough for 50+B+I+H2; 100 GB for 181+B+I+H2
  runtime: "12:00:00"

plotting:
  map:
    boundaries: [-11, 30, 34, 71]
    color_geomap:
      ocean: white
      land: whitesmoke
  costs_max: 10
  costs_threshold: 0.2
  energy_max: 20000
  energy_min: -20000
  energy_threshold: 15
  vre_techs:
  - onwind
  - offwind-ac
  - offwind-dc
  - solar
  - ror
  renewable_storage_techs:
  - PHS
  - hydro
  conv_techs:
  - OCGT
  - CCGT
  - Nuclear
  - Coal
  storage_techs:
  - hydro+PHS
  - battery
  - H2
  load_carriers:
  - AC load
  AC_carriers:
  - AC line
  - AC transformer
  link_carriers:
  - DC line
  - Converter AC-DC
  heat_links:
  - heat pump
  - resistive heater
  - CHP heat
  - CHP electric
  - gas boiler
  - central heat pump
  - central resistive heater
  - central CHP heat
  - central CHP electric
  - central gas boiler
  heat_generators:
  - gas boiler
  - central gas boiler
  - solar thermal collector
  - central solar thermal collector
  tech_colors:
    SMR CC: "darkblue"
    gas for industry CC: "brown"
    process emissions CC: "gray"
    CO2 pipeline: "gray"
    onwind: "dodgerblue"
    onshore wind: "#235ebc"
    offwind: "#6895dd"
    offshore wind: "#6895dd"
    offwind-ac: "c"
    offshore wind (AC): "#6895dd"
    offwind-dc: "#74c6f2"
    offshore wind (DC): "#74c6f2"
    wave: '#004444'
    hydro: '#3B5323'
    hydro reservoir: '#3B5323'
    ror: '#78AB46'
    run of river: '#78AB46'
    hydroelectricity: 'blue'
    solar: "orange"
    solar PV: "#f9d002"
    solar thermal: coral
    solar rooftop: '#ffef60'
    OCGT: wheat
    OCGT marginal: sandybrown
    OCGT-heat: '#ee8340'
    gas boiler: '#ee8340'
    gas boilers: '#ee8340'
    gas boiler marginal: '#ee8340'
    gas-to-power/heat: 'brown'
    gas: brown
    natural gas: brown
    SMR: '#4F4F2F'
    oil: '#B5A642'
    oil boiler: '#B5A677'
    lines: k
    transmission lines: k
    H2: m
    H2 liquefaction: m
    hydrogen storage: m
    battery: slategray
    battery storage: slategray
    home battery: '#614700'
    home battery storage: '#614700'
    Nuclear: r
    Nuclear marginal: r
    nuclear: r
    uranium: r
    Coal: k
    coal: k
    Coal marginal: k
    Lignite: grey
    lignite: grey
    Lignite marginal: grey
    CCGT: '#ee8340'
    CCGT marginal: '#ee8340'
    heat pumps: '#76EE00'
    heat pump: '#76EE00'
    air heat pump: '#76EE00'
    ground heat pump: '#40AA00'
    power-to-heat: 'red'
    resistive heater: pink
    Sabatier: '#FF1493'
    methanation: '#FF1493'
    power-to-gas: 'purple'
    power-to-liquid: 'darkgreen'
    helmeth: '#7D0552'
    DAC: 'deeppink'
    co2 stored: '#123456'
    CO2 sequestration: '#123456'
    CC: k
    co2: '#123456'
    co2 vent: '#654321'
    agriculture heat: '#D07A7A'
    agriculture machinery oil: '#1e1e1e'
    agriculture machinery oil emissions: '#111111'
    agriculture electricity: '#222222'
    solid biomass for industry co2 from atmosphere: '#654321'
    solid biomass for industry co2 to stored: '#654321'
    solid biomass for industry CC: '#654321'
    gas for industry co2 to atmosphere: '#654321'
    gas for industry co2 to stored: '#654321'
    Fischer-Tropsch: '#44DD33'
    kerosene for aviation: '#44BB11'
    naphtha for industry: '#44FF55'
    land transport oil: '#44DD33'
    water tanks: '#BBBBBB'
    hot water storage: '#BBBBBB'
    hot water charging: '#BBBBBB'
    hot water discharging: '#999999'
    # CO2 pipeline: '#999999'
    CHP: r
    CHP heat: r
    CHP electric: r
    PHS: g
    Ambient: k
    Electric load: b
    Heat load: r
    heat: darkred
    rural heat: '#880000'
    central heat: '#b22222'
    decentral heat: '#800000'
    low-temperature heat for industry: '#991111'
    process heat: '#FF3333'
    heat demand: darkred
    electric demand: k
    Li ion: grey
    district heating: '#CC4E5C'
    retrofitting: purple
    building retrofitting: purple
    BEV charger: grey
    V2G: grey
    land transport EV: grey
    electricity: k
    gas for industry: '#333333'
    solid biomass for industry: '#555555'
    industry electricity: '#222222'
    industry new electricity: '#222222'
    process emissions to stored: '#444444'
    process emissions to atmosphere: '#888888'
    process emissions: '#222222'
    oil emissions: '#666666'
    industry oil emissions: '#666666'
    land transport oil emissions: '#666666'
    land transport fuel cell: '#AAAAAA'
    biogas: '#800000'
    solid biomass: '#DAA520'
    today: '#D2691E'
    shipping: '#6495ED'
    shipping oil: "#6495ED"
    shipping oil emissions: "#6495ED"
    electricity distribution grid: 'y'
    solid biomass transport: green
    H2 for industry: "#222222"
    H2 for shipping: "#6495ED"
    biomass EOP: "green"
    biomass: "green"
    high-temp electrolysis: "magenta"
