name: CI

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  schedule:
  - cron: "0 5 * * TUE"

env:
  CACHE_NUMBER: 2  # Change this value to manually reset the environment cache

jobs:
  build:
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
        # - windows-latest

    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v2

    - name: Fill submodule
      run: |
        git submodule update --init

    - name: Setup micromamba
      uses: mamba-org/setup-micromamba@v1
      with:
        micromamba-version: latest
        environment-file: pypsa-earth/envs/environment.yaml
        log-level: debug
        init-shell: bash
        cache-environment: true
        cache-downloads: true

    - name: Set cache dates
      run: |
        echo "WEEK=$(date +'%Y%U')" >> $GITHUB_ENV

    - name: Cache data and cutouts folders
      uses: actions/cache@v3
      with:
        path: |
          data
          cutouts
        key: data-cutouts-${{ env.WEEK }}-${{ env.CACHE_NUMBER }}


    - name: Conda list
      run: conda list

    - name: Run Test
      run: make test
